source_url: "https://www.sueddeutsche.de/muenchen/fuerstenfeldbruck"
skip_patterns:
  - "/impressum"
  - "/datenschutz"
  - "/agb"
  - "/login"
  - "/abo"
  - "/archiv"
  - "/suche"
  - "/kontakt"
  - "/newsletter"
  - "/shop"
  - "/mediadaten"
  - "/preise"
  - "/abo-angebote"
  - "/meine-zeitung"
  - "/abo-verwaltung"
  - "/thema"
  - "/rubrik"
  - "/sz-"
  - "/szplus"
  - "/sz-aktiv"
  - "/sz-abo"
article_sections:
  - "/fuerstenfeldbruck"
  - "/landkreis"
  - "/politik"
  - "/sport"
  - "/leben"
  - "/wirtschaft"
  - "/kultur"
  - "/veranstaltungen"
path_validation:
  min_parts: 3
  required_parts:
    - "muenchen"
    - "fuerstenfeldbruck"
  exclude_parts:
    - "index"
    - "startseite"
    - "thema"
    - "rubrik" 